{
 "items":[
  {"id":"Star Wars Episode VII - The Force Awakens",
   "label": "Star Wars Episode VII - The Force Awakens",
   "year":"2015",
   "gross":922,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Avatar",
   "label": "Avatar",
   "year":"2009",
   "gross":761,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Jurassic World",
   "label": "Jurassic World",
   "year":"2015",
   "gross":652,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"The Avengers",
   "label": "The Avengers",
   "year":"2012",
   "gross":623,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"The Dark Knight",
   "label": "The Dark Knight",
   "year":"2008",
   "gross":533,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Star Wars Episode I - The Phantom Menace",
   "label": "Star Wars Episode I - The Phantom Menace",
   "year":"1999",
   "gross":475,
   "genre": "action",
   "rating":"pg"
  },
  {"id":"Star Wars",
   "label":"Star Wars",
   "year":"1977",
   "gross":461,
   "genre": "action",
   "rating":"pg"
  },
  {"id":"Avengers: Age of Ultron",
   "label":"Avengers: Age of Ultron",
   "year":"2015",
   "gross":459,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"The Dark Knight Rises",
   "label":"The Dark Knight Rises",
   "year":"2012",
   "gross":448,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Pirates of the Caribbean: Dead Man's Chest",
   "label":"Pirates of the Caribbean: Dead Man's Chest",
   "year":"2006",
   "gross":423,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Iron Man 3",
   "label":"Iron Man 3",
   "year":"2013",
   "gross":409,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Spider-Man",
   "label":"Spider-Man",
   "year":"2002",
   "gross":404,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Transformers: Revenge of the Fallen",
   "label":"Transformers: Revenge of the Fallen",
   "year":"2009",
   "gross":402,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Star Wars Episode III - Revenge of the Sith",
   "label":"Star Wars Episode III - Revenge of the Sith",
   "year":"2005",
   "gross":380,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Spider-Man 2",
   "label":"Spider-Man 2",
   "year":"2004",
   "gross":373,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Transformers: Dark of the Moon",
   "label":"Transformers: Dark of the Moon",
   "year":"2011",
   "gross":352,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"American Sniper",
   "label":"American Sniper",
   "year":"2014",
   "gross":350,
   "genre": "action",
   "rating":"r"
  },
  {"id":"Furious 7",
   "label":"Furious 7",
   "year":"2015",
   "gross":350,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Spider-Man 3",
   "label":"Spider-Man 3",
   "year":"2007",
   "gross":337,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Guardians of the Galaxy",
   "label":"Guardians of the Galaxy",
   "year":"2014",
   "gross":333,
   "genre": "action",
   "rating":"pg13"
  },
  {"id":"Shrek 2",
   "label":"Shrek 2",
   "year":"2004",
   "gross":436,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"Toy Story 3",
   "label":"Toy Story 3",
   "year":"2010",
   "gross":415,
   "genre": "comedy",
   "rating":"g"
  },
  {"id":"Frozen",
   "label":"Frozen",
   "year":"2013",
   "gross":401,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"Finding Nemo",
   "label":"Finding Nemo",
   "year":"2003",
   "gross":381,
   "genre": "comedy",
   "rating":"g"
  },
  {"id":"Despicable Me 2",
   "label":"Despicable Me 2",
   "year":"2013",
   "gross":368,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"Inside Out",
   "label":"Inside Out",
   "year":"2015",
   "gross":356,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"Minions",
   "label":"Minions",
   "year":"2015",
   "gross":336,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"Shrek the Third",
   "label":"Shrek the Third",
   "year":"2007",
   "gross":321,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"Up",
   "label":"Up",
   "year":"2009",
   "gross":293,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"Monsters, Inc.",
   "label":"Monsters, Inc.",
   "year":"2001",
   "gross":290,
   "genre": "comedy",
   "rating":"g"
  },
  {"id":"Home Alone",
   "label":"Home Alone",
   "year":"1990",
   "gross":286,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"Meet the Fockers",
   "label":"Meet the Fockers",
   "year":"2004",
   "gross":279,
   "genre": ["comedy","romance"],
   "rating":"pg13"
  },
  {"id":"The Hangover",
   "label":"The Hangover",
   "year":"2009",
   "gross":277,
   "genre": "comedy",
   "rating":"ur"
  },
  {"id":"Monsters University",
   "label":"Monsters University",
   "year":"2013",
   "gross":"268",
   "genre": "comedy",
   "rating":"g"
  },
  {"id":"Shrek",
   "label":"Shrek",
   "year":"2001",
   "gross":268,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"How the Grinch Stole Christmas",
   "label":"How the Grinch Stole Christmas",
   "year":"2000",
   "gross":260,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"The Lego Movie",
   "label":"The Lego Movie",
   "year":"2014",
   "gross":258,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"The Hangover Part II",
   "label":"The Hangover Part II",
   "year":"2011",
   "gross":254,
   "genre": "comedy",
   "rating":"r"
  },
  {"id":"Despicable Me",
   "label":"Despicable Me",
   "year":"2010",
   "gross":252,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"Night at the Museum",
   "label":"Night at the Museum",
   "year":"2010",
   "gross":252,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"Titanic",
   "label":"Titanic",
   "year":"1997",
   "gross":659,
   "genre": "romance",
   "rating":"pg13"
  },
  {"id":"Forrest Gump",
   "label":"Forrest Gump",
   "year":"1994",
   "gross":330,
   "genre": "romance",
   "rating":"pg13"
  },
  {"id":"The Twilight Saga: Eclipse",
   "label":"The Twilight Saga: Eclipse",
   "year":"2010",
   "gross":301,
   "genre": "romance",
   "rating":"pg13"
  },
  {"id":"The Twilight Saga: New Moon",
   "label":"The Twilight Saga: New Moon",
   "year":"2009",
   "gross":279,
   "genre": "romance",
   "rating":"pg13"
  },
  {"id":"The Twilight Saga: Breaking Dawn - Part 2",
   "label":"The Twilight Saga: Breaking Dawn - Part 2",
   "year":"2012",
   "gross":292,
   "genre": "romance",
   "rating":"pg13"
  },
  {"id":"The Twilight Saga: Breaking Dawn - Part 1",
   "label":"The Twilight Saga: Breaking Dawn - Part 1",
   "year":"2011",
   "gross":281,
   "genre": "romance",
   "rating":"pg13"
  },
  {"id":"My Big Fat Greek Wedding",
   "label":"My Big Fat Greek Wedding",
   "year":"2002",
   "gross":241,
   "genre": ["romance", "comedy"],
   "rating":"pg"
  },
  {"id":"Maleficent",
   "label":"Maleficent",
   "year":"2014",
   "gross":241,
   "genre": ["romance", "action"],
   "rating":"pg"
  },
  {"id":"Cast Away",
   "label":"Cast Away",
   "year":"2000",
   "gross":234,
   "genre": "romance",
   "rating":"pg13"
  },
  {"id":"Beauty and the Beast",
   "label":"Beauty and the Beast",
   "year":"1991",
   "gross":219,
   "genre": "romance",
   "rating":"g"
  },
  {"id":"King Kong",
   "label":"King Kong",
   "year":"2005",
   "gross":218,
   "genre": ["romance", "action"],
   "rating":"pg13"
  },
  {"id":"Ghost",
   "label":"Ghost",
   "year":"2011",
   "gross":218,
   "genre": "romance",
   "rating":"pg13"
  },
  {"id":"Aladdin",
   "label":"Aladdin",
   "year":"1992",
   "gross":217,
   "genre": "romance",
   "rating":"g"
  },
  {"id":"Wedding Crashers",
   "label":"Wedding Crashers",
   "year":"2005",
   "gross":209,
   "genre": ["romance", "comedy"],
   "rating":"r"
  },
  {"id":"Cinderella",
   "label":"Cinderella",
   "year":"2015",
   "gross":201,
   "genre": "romance",
   "rating":"pg"
  },
  {"id":"Tangled",
   "label":"Tangled",
   "year":"2010",
   "gross":201,
   "genre": "comedy",
   "rating":"pg"
  },
  {"id":"Mr. & Mrs. Smith",
   "label":"Mr. & Mrs. Smith",
   "year":"2005",
   "gross":186,
   "genre": ["romance", "action"],
   "rating":"ur"
  }
 ]
}